# =====================================================
# HERO INFO
# =====================================================
HERO_INFO = {
    "wukong": {"full": "Wukong", "short": "Wuk"},
    "louis ix": {"full": "Louis IX", "short": "Louis"},
    "tutankhamun": {"full": "Tutankhamun", "short": "Tut"},
    "khubilai khan": {"full": "Khubilai Khan", "short": "Khan"},
    "manco": {"full": "Manco", "short": "Manco"},
    "alexander the great": {"full": "Alexander The Great", "short": "Alex"},
    "hippolyta": {"full": "Hippolyta", "short": "Hip"},
    "william": {"full": "William", "short": "Will"},
    "attila the hun": {"full": "Attila The Hun", "short": "Attila"},
    "saladin": {"full": "Saladin", "short": "Sal"},
    "muhammad ii": {"full": "Muhammad II", "short": "Muh"},
    "siegfried": {"full": "Siegfried", "short": "Sieg"},
    "peter the great": {"full": "Peter The Great", "short": "Peter"},
    "ramesses ii": {"full": "Ramesses II", "short": "Ram"},
    "hannibal barca": {"full": "Hannibal Barca", "short": "Hann"},
    "herald": {"full": "Herald", "short": "Herald"},
    "frederick": {"full": "Frederick", "short": "Fred"},
    "loki": {"full": "Loki", "short": "Loki"},
    "hammurabi": {"full": "Hammurabi", "short": "Ham"},
    "himiko": {"full": "Himiko", "short": "Him"},
    "empress wu": {"full": "Empress Wu", "short": "Wu"},
    "baldwin iv": {"full": "Baldwin IV", "short": "Bald"},
    "merlin": {"full": "Merlin", "short": "Mer"},
    "cleopatra": {"full": "Cleopatra", "short": "Cleo"},
    "bjorn": {"full": "Bjorn", "short": "Bjorn"},
    "king arthur": {"full": "King Arthur", "short": "Arthur"},
    "el cid": {"full": "El Cid", "short": "Cid"},
    "leonidas": {"full": "Leonidas", "short": "Leo"},
    "julius caesar": {"full": "Julius Caesar", "short": "JC"},
    "charles": {"full": "Charles", "short": "Char"},
    "ragnar": {"full": "Ragnar", "short": "Rag"},
    "trajan": {"full": "Trajan", "short": "Traj"},
    "tokugawa": {"full": "Tokugawa", "short": "Toku"},
    "gilgamesh": {"full": "Gilgamesh", "short": "Gil"},
    "elizabeth bathory": {"full": "Elizabeth Bathory", "short": "Liz"},
    "yoshitsune": {"full": "Yoshitsune", "short": "Yoshi"},
    "yi seong-gye": {"full": "Yi Seong-Gye", "short": "Yi"},
    "ashoka": {"full": "Ashoka", "short": "Ash"},
    "genghis khan": {"full": "Genghis Khan", "short": "GK"},
    "arash": {"full": "Arash", "short": "Arash"},
    "atalanta": {"full": "Atalanta", "short": "Ata"},
    "seondeok": {"full": "Seondeok", "short": "Seon"},
    "margaret i": {"full": "Margaret I", "short": "Marg"},
    "nebuchadnezzar ii": {"full": "Nebuchadnezzar II", "short": "Neb"},
}

# =====================================================
# HERO PRICE
# =====================================================
HERO_PRICE = {
    "wukong": "🐳 Whale Tier",
    "louis ix": "❄️ KVK Exclusive",
    "tutankhamun": "💰 High Tier",
    "khubilai khan": "💰 High Tier",
    "manco": "💰 High Tier",
    "alexander the great": "👑📜 Premium/Gems",
    "hippolyta": "🆓 Free-to-Play Friendly",
    "william": "🆓 Free-to-Play Friendly",
    "attila the hun": "👑📜 Premium/Gems",
    "saladin": "👑📜 Premium/Gems",
    "muhammad ii": "💰 High Tier",
    "siegfried": "💰 High Tier",
    "peter the great": "🆓 Free-to-Play Friendly",
    "ramesses ii": "👑📜 Premium/Gems",
    "hannibal barca": "🆓 Free-to-Play Friendly",
    "herald": "🆓 Free-to-Play Friendly",
    "frederick": "🆓 Free-to-Play Friendly",
    "loki": "🐳 Whale Tier",
    "hammurabi": "👑 Premium",
    "himiko": "💰 High Tier",
    "empress wu": "🆓 Free-to-Play Friendly",
    "baldwin iv": "👑📜 Premium/Gems",
    "merlin": "💵 Low/Mid Spending",
    "cleopatra": "🆓 Free-to-Play Friendly",
    "bjorn": "💰 High Tier",
    "king arthur": "🆓 Free-to-Play Friendly",
    "el cid": "👑📜 Premium/Gems",
    "leonidas": "🆓 Free-to-Play Friendly",
    "julius caesar": "🆓 Free-to-Play Friendly",
    "charles": "👑📜 Premium/Gems",
    "ragnar": "❄️ KVK Exclusive",
    "trajan": "❄️ KVK Exclusive",
    "tokugawa": "❄️ KVK Exclusive",
    "gilgamesh": "🆓 Free-to-Play Friendly",
    "elizabeth bathory": "💰👑📜 Premium/Gems",
    "yoshitsune": "🆓 Free-to-Play Friendly",
    "yi seong-gye": "🆓 Free-to-Play Friendly",
    "ashoka": "🆓 Free-to-Play Friendly",
    "genghis khan": "👑📜 Premium/Gems",
    "arash": "🆓 Free-to-Play Friendly",
    "atalanta": "👑 Premium",
    "seondeok": "❄️ KVK Exclusive",
    "margaret i": "❄️ KVK Exclusive",
    "nebuchadnezzar ii": "💰 High Tier",
}
